# -*- coding: utf-8 -*-
"""hybrid search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12z9fsDSl84fVlxImAqGfsN874e8L4bKw
"""

pip install -U langchain-community

pip install -U langchain-community

pip install faiss-cpu

pip install rank_bm25

from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from langchain.schema import Document

# Sample documents
docs = [
    Document(page_content="Best budget phones under ₹10,000"),
    Document(page_content="Smartphones with long battery life"),
    Document(page_content="Premium phones with fast processors"),
]

# Embedding model
embedding = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
faiss_db = FAISS.from_documents(docs, embedding)

# Lexical retriever (BM25)
bm25 = BM25Retriever.from_documents(docs)

# Hybrid retriever
hybrid = EnsembleRetriever(
    retrievers=[faiss_db.as_retriever(), bm25],
    weights=[0.5, 0.5]
)

# Query
results = hybrid.get_relevant_documents("cheap phone with good battery")

# Print results
for i, r in enumerate(results):
    print(f"{i+1}. {r.page_content}")